### PR TITLE
Bug fix - forcing CUDA support

### PR DESCRIPTION
**Pull request by MarcusLoppe**

### CODE REVIEW

**Comment by MarcusLoppe** [comment]
@lucidrains  same thing with huggingface :)

**Comment by fire** [comment]
Cheers!

**Review by lucidrains — APPROVED** [review]

**Comment by MarcusLoppe** [comment]
@lucidrains 
Tada !
https://huggingface.co/MarcusLoren/MeshGPT-preview

**Comment by lucidrains** [comment]
congrats Marcus!

**Pull request merged**
